### ISSUE TITLE
Information on flashing

### ISSUE THREAD

**Issue by Duckle29** [spoter368/os3m-firmware#4]
Hi there

I recently got my board together and hoped I could flash it over the built in USB bootloader. It works, kinda, but no, not really :laughing: 

Using STM32CubeProgrammer, I can connect and flash and start the application, but on power-on, it'll go back to the USB bootloader.

Are there some special sauce in where to place the application start address or similar? 

I will bring an st-link or a segger home from work to try and flash it through stm32 for vscode later, but can't today as I'm out of time.

I also think making it work with the USB-DFU bootloader would be nifty.

**Comment by Duckle29** [comment]
Here's a video of it:
https://paste.mikkel.cc/khRvsiV2/+inline

I had to run STM32CubeProgrammer as root for it to detect the DFU bootloader, but I'm sure that's just a udev rule away from working in userland too

**Comment by spoter368** [comment]
Sounds like you may have an earlier revision of the board, and are suffering from https://github.com/spoter368/os3m-hardware/issues/9. I'll upload a how_to_flash.md today to clear up any uncertainty people are having. Sorry about that!

**Comment by spoter368** [comment]
Just published a guide on how to flash the board, and pushed a release with the latest binary! Check it out and let me know if that helps.

**Comment by hotsgit** [comment]
Thanks for the guide. I was tempted to create an Issue before this since I was monstrously confused.

If you haven't written a guide for how exactly to order from JLCPCB, want me to write one for you to use/modify?

**Comment by hotsgit** [comment]
How long should Step 3's download take? No messagebox appeared, and mine has been repeatedly sending these logs for 15 mins. I can't click on OB either. I stopped it but the board doesn't seem to react differently.

I'm on an older revision of the board, I doubt they matter for this but I cut the shorted UART traces already.
![image](https://github.com/spoter368/os3m-firmware/assets/52811817/26999b4f-3e2e-44ae-8a1b-eea310d05267)
![image](https://github.com/spoter368/os3m-firmware/assets/52811817/29eb6fd2-9003-4452-ab17-9cde4f12bb93)

I connected the board briefly yesterday before downloading the STM32 program, hopefully that didn't cause an issue, no idea.

**Comment by spoter368** [comment]
For sure! Feel free to write the ordering guide and open a PR. If it looks good I'll approve.

Secondly, that is very weird, my download took on the order of one to two seconds. Do you have an STLINK? I also did not get any of those messages about DFU state, so I'm really lost, sorry!

**Comment by hotsgit** [comment]
My DFU messages may just be because I set Verbosity to 3. I noticed my version of OS3M_Mouse.elf is a different size than the one in your guide (0x516c); maybe that doesn't matter. My board still has the original device memory after stopping, so I assume it wrote nothing.

I don't have an STLink but I do have an FT232R. Should I bodge some UART wires and try Addendum A in your guide? Alternately can UART be used to flash?

**Comment by spoter368** [comment]
Addendum A only applies if you are running the OS3M firmware on the mouse, and it simply jumps back to the bootloader where you _in theory_ should be able to use DFU to flash a new binary. If DFU isn't working, I'm not sure what else to do. An STLINK is probably the best way to recover the MCU. You can get an STLINK off amazon for like $6 so I recommend that. Sorry I can't help more

**Comment by hotsgit** [comment]
Just an update on this @spoter368, sorry I got too busy to write that guide on how to order. In other threads I see that the design has had several updates/offshoots, but I'll start writing one for the main version.

I bought the cheapest ST-Link off amazon but it had a Geehy chip which means it didn't work with the Cube Programmer (only works with ST-LINK Utility, even after upgrading firmware), so I couldn't open the ._elf_ file. In my country I had to buy a $15 one based off amazon reviews which said it worked with Cube Programmer, then it worked.

If you think others will encounter this issue you can mention in your guide "You can buy an ST-Link on Amazon for $6-$15 but check the reviews for whether it works with Cube Programmer". The pic below isn't totally useful for buyers since amazon pages have wrong photos and may change what they sell.
![ST-Link Good vs Bad](https://github.com/spoter368/os3m-firmware/assets/52811817/a877a0d8-c387-4fd7-9185-219d9986153b)
